---
apiVersion: v1
kind: Service
metadata:
  name: arattai-lb-svc
  labels:
    app: arattai-app
    env: staging
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
     app: arattai-app
    
